name = "personaldesign"
pages_build_output_dir = "public"
compatibility_date = "2024-03-20"

[[d1_databases]]
binding = "DB"
database_name = "leaderboard-db"
database_id = "8f306920-41f4-47d0-9b0c-9613aabc98b7"
